services:
  npm:
    build: .
    volumes:
      - .:/app
    profiles: [cli]

  dev-server:
    build: .
    command: ["run", "dev"]
    ports:
      - 3000:8000
    volumes:
      - .:/app

  prod-server:
    build: .
    command: ["run", "preview"]
    ports:
      - 3001:3000
    volumes:
      - .:/app
    profiles: [prod-server]
